import = [
    "~/.config/alacritty/cyberdream.toml"
]

[window]
opacity = 0.5

  [window.padding]
  x = 3
  y = 3

[colors.primary]
background = '#010E17'

[font]
size = 11.25

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "PageDown"
action = "None"

[[keyboard.bindings]]
key = "PageUp"
action = "None"

[[keyboard.bindings]]
key = "M"
mods = "Super"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "X"
mods = "Super"
action = "Quit"

[[keyboard.bindings]]
key = "Period"
mods = "Control"
chars = "g_a"

[[keyboard.bindings]]
key = "E"
mods = "Control"
action = "CreateNewWindow"
